conf/app.conf
feat: Se agregan las variables globales para cumplidos dve
=> feat: Se agregan las variables globales para cumplidos dve

docker-compose.yml
feat: Se corrige el nombre de resoluciones_mid_v2 por cumplidos_dve_mid
=> feat: Se corrige el nombre de resoluciones_mid_v2 por cumplidos_dve_mid

.gitignore, README.md, swagger/swagger.json, swagger/swagger.yml
feat: Se modifica el archivo .gitignore para que se adjunte el archivo .yml del swagger
=> feat: Se modifica el archivo .gitignore

conf/app.conf, helpers/pago.go
feat: Se corrigen las variables de entorno usadas y donde se hace el respectivo llamado de los cambios
=> feat: Se corrigen las variables de entorno usadas

conf/app.conf, helpers/academica.go, helpers/documentos.go, helpers/pago.go, helpers/utilidades.go, models/area_tipo.go, models/pago_mensual.go, models/parametro.go, models/tipo_parametro.go
feat: Se agrega una nueva variable de entorno y se realizar cambios con respecto a algunos controladores, asi mismo se crean varios modelos necesarios, con el fin de acceder a los servicios de cumplidos dve
=> feat: Se agrega una nueva variable de entorno y se realizar cambios

controllers/aprobacion_documentos.go, helpers/documentos.go, helpers/utilidades.go
feat: Se modifica el método asociado a la aprobación de múltiples solicitudes de cumplidos, y también el método para obtener las peticiones del supervisor, por otra parte, se quitan ciertas impresiones de consola, que ya no se requieren para depuración
=> feat: Se modifica el metodo asociado a la aprobacion de multiples

conf/app.conf, helpers/academica.go, helpers/documentos.go, helpers/pago.go, helpers/utilidades.go, models/pago_mensual.go, models/resolucion.go, models/resolucion_vinculacion_docente.go, models/vinculacion_docente.go
feat: Se realiza el cambio a consumo de resoluciones y la aplicacion de la libreria UTILIDADES, de manera que cambian varias cosas del modelo y asi mismo se agrega la variable de entorno hacia resoluciones.
=> feat: Se realiza el cambio a consumo de resoluciones y la aplicacion de UTILIDADES

README.md
feat: Se da un Enter en readme.md
=> feat: Se da un Enter en readme.md

helpers/academica.go, helpers/pago.go
feat: Se realiza una corrección con respecto a la librería fmt, para quitar un mensaje que muestra los datos en consola, y se corrige el IdDependencia para el CargaContratosDocente
=> feat: Se realiza una corrección con respecto a la librería fmt

.drone.yml, controllers/aprobacion_documentos.go, controllers/aprobacion_pago.go, controllers/informacion_academica.go
feat: Se realizan cambios en el archivo Drone
=> feat: Se realizan cambios en el archivo Drone

controllers/aprobacion_documentos.go, controllers/aprobacion_pago.go, helpers/documentos.go
feat: Se agrega la  importación de fmt
=> feat: Se agrega la  importación de fmt

controllers/aprobacion_pago.go, helpers/pago.go, routers/commentsRouter_controllers.go, swagger/swagger.json, swagger/swagger.yml
feat: Se desarrolla la logica asociada a generar PDF por parte del Ordenador del Gasto
=> feat: Se desarrolla la logica asociada a generar PDF por parte del Ordenador del Gasto

helpers/pago.go
feat: Se realiza un pequeño cambio dando espacios
=> feat: Se realiza un pequeño cambio dando espacios

controllers/aprobacion_pago.go, helpers/pago.go
feat: Primer intento de solución al error de ambiente de pruebas
=> feat: Primer intento de solución al error de ambiente de pruebas

helpers/documentos.go, helpers/pago.go
feat: Se coloca en comentario la logica de los docente que no cumplieron con los documentos
=> feat: Se coloca en comentario la logica de los docente que no cumplieron con los documentos

controllers/aprobacion_documentos.go, helpers/documentos.go
feat: Se colocan panic para que se puedan visualizar en ambiente de pruebas
=> feat: Se colocan panic para que se puedan visualizar en ambiente de pruebas

controllers/aprobacion_documentos.go, helpers/documentos.go
feat: Se desvincula la función para buscar los docentes del certificado al momento de generarlo
=> feat: Se desvincula la función para buscar los docentes de los certificados

helpers/documentos.go
feat: Se agregan impresiones para ver el valor de las variables
=> feat: Se agregan impresiones para ver el valor de las variables

helpers/documentos.go
feat: Se agregan banderas de impresión
=> feat: Se agregan banderas de impresión

helpers/documentos.go
feat: Se agregan mas banderas de impresión
=> feat: Se agregan mas banderas de impresión

helpers/documentos.go
feat: Se agregan aún mas banderas de impresión
=> feat: Se agregan aún mas banderas de impresión

helpers/documentos.go
feat: Se cambio la función de WriteAligned por MultiCell.
=> feat: Se cambio la función de WriteAligned por MultiCell.

helpers/documentos.go
feat: Se cambio todas las funciones de WriteAligned por MultiCell.
=> feat: Se cambio todas las funciones de WriteAligned por MultiCell.

helpers/documentos.go
feat: Se  hace el cambio de un ultimo WriteAligned por MultiCell.
=> feat: Se  hace el cambio de un ultimo WriteAligned por MultiCell.

helpers/utilidades.go
Se imprime la URL que se forma en GetRequestNew y GetRequestLegacy
=> Se imprime la URL que se forma en GetRequestNew y GetRequestLegacy

Dockerfile, controllers/aprobacion_documentos.go, helpers/documentos.go, helpers/utilidades.go
feat: Se agrega la linea para la corrección de los PDF en el archivo DockerFile, se quitan las banderas de impresión y se restaura la función que consulta los docentes que no cumplieron con los cumplidos.
=> feat: Se agrega la linea para la corrección de los PDF en el archivo DockerFile

helpers/pago.go
feat: Se realiza el cambio de WriteAligned a MultiCell para una mejor visualización
=> feat: Se realiza el cambio de WriteAligned a MultiCell para una mejor visualización

xray/xray.go
fix: corrección de archivos Xray para envio de trazas
=> fix: corrección de archivos Xray para envio de trazas

conf/app.conf, xray/xray.go
=> fix: variable de entorno XRAY

helpers/documentos.go
fix: Se realiza la corrección relacionada a la generación de certificados por parte del Coordinador.
=> fix: Se realiza la corrección relacionada a la generación de certificados.

helpers/academica.go
fix: Se cambia la variable llamada CumplidosDveAcademica por ahora para hacer pruebas
=> fix: Se cambia la variable llamada CumplidosDveAcademica

helpers/academica.go, helpers/documentos.go
fix: corrección de envio de trazas a AWS
=> fix: corrección de envio de trazas a AWS

helpers/academica.go
fix: Se realizan cambios para sincronización entre ramas.
=> fix: Se realizan cambios para sincronización entre ramas.

helpers/pago.go
fix: Se quita un espacio en el archivo helper llamado pago.
=> fix: Se quita un espacio en el archivo helper llamado pago.

helpers/documentos.go
fix: Se agregan dos estados nuevos al momento de generar el certificado por parte del coordinador.
=> fix: Se agregan dos estados nuevos al momento de generar el certificado

helpers/documentos.go
fix: Se corrige la lógica asociada a la generación de los certificados por parte del coordinador.
=> fix: Se corrige la lógica asociada a la generación de los certificados

helpers/documentos.go
fix: Se corrige la lógica asociada a la generación de los certificados por parte del coordinador.
=> fix: Se corrige la lógica asociada a la generación de los certificados por parte del coordinador.

models/cumplido_rp.go
fix: Se cambia el tipo de dato del campo MedicinaPrepagadaUvt, pasa de ser int a float64.
=> fix: Se cambia el tipo de dato del campo MedicinaPrepagadaUvt

models/contrato.go, models/cumplido_rp.go
fix: Se actualiza el tipo de datos y estructura manejada en titan
=> fix: Se actualiza el tipo de datos y estructura manejada en titan

helpers/pago.go, models/contrato.go, models/cumplido_rp.go
fix: Se agrega esa pequeña línea de código para que retorne todas las solicitudes relacionadas al ordenador y no solo 10.
=> fix: listar todas las solicitudes del ordenador del gasto

helpers/pago.go
fix: Se agrega esa pequeña línea de código para que retorne todas las solicitudes relacionadas al ordenador y no solo 10.
=> fix: Visualización de peticiones en el ordenador

helpers/pago.go
- Se corrige la consulta que asigna al ordenador del gasto al momento de realizar la aprobación por parte del supervisor.
=> fix: udistrital/cumplidos_dve_cliente#129	Correccion_ordenador_del_gasto

helpers/pago.go
- Se actualiza el Endpoints para la generación de certificados.
=>  udistrital/cumplidos_dve_cliente#129  Corrección_de_endpoint_para_certificados_ordenador

helpers/pago.go
- Se cambia la dependencia que aparece en el certificado de cumplimiento de decano, se pasa de División de recursos Humanos a Oficina de Talento Humano
=> fix: Se cambia la dependencia que aparece en el certificado de cumplimiento de decano
